// Dados dos prompts do livro "Engenharia de Prompts para Escrita Acadêmica com IA Generativa".
// Extraídos da versão anterior da página (prompts_engenharia_de_prompts.html.bk).
// Títulos e técnicas são provisórios: o conteúdo original só trazia uma legenda por figura.

window.ESTRUTURA = [
  {
    parte: "Parte II",
    titulo: "Prompts para escrita e revisão",
    capitulos: [
      { numero: 4, titulo: "Revisão de Texto com IA" },
      { numero: 5, titulo: "Análise de Artigos Científicos com IA" },
      { numero: 6, titulo: "Estilos de Escrita Acadêmica com IA" },
      { numero: 7, titulo: "Papéis e Personas na Escrita Acadêmica com IA" },
      { numero: 8, titulo: "Ajustes de Resposta do Modelo" },
      { numero: 9, titulo: "Recuperação de Fontes e Conexão com Dados" },
      { numero: 10, titulo: "Geração de Elementos Visuais e Analíticos com IA" },
      { numero: 11, titulo: "Exploração Criativa e Reflexiva com IA" }
    ]
  },
  {
    parte: "Parte III",
    titulo: "Personas e papéis",
    capitulos: [
      { numero: 12, titulo: "Criação e Uso de Personas na Escrita Acadêmica" }
    ]
  },
  {
    parte: "Parte IV",
    titulo: "Estratégias avançadas",
    capitulos: [
      { numero: 13, titulo: "Prompt Chaining e Raciocínio em Etapas" },
      { numero: 14, titulo: "Few-shot Prompting e Exemplos Guiados" }
    ]
  },
  {
    parte: "Parte V",
    titulo: "Reflexões finais",
    capitulos: [
      { numero: 15, titulo: "Ética, Autoria e Originalidade na Era da IA" }
    ]
  }
];

window.PROMPTS = [
  { id: "fig-1", figura: 1, capitulo: 4, titulo: "Reescrita de texto em tom acadêmico", tecnicas: ["reescrita"],
    prompt: "Reescreva o parágrafo a seguir em tom acadêmico, deixando-o mais claro e coeso: A Ciência da Computação é o campo do conhecimento que estuda os fundamentos teóricos e práticos da computação e da tecnologia da informação. Ela envolve o desenvolvimento de softwares e sistemas eficientes, com ênfase em algoritmos, programação, redes, segurança da informação, inteligência artificial e análise de dados.",
    resposta: "A Ciência da Computação constitui um campo interdisciplinar dedicado ao estudo dos fundamentos teóricos e práticos da computação e das tecnologias da informação. Seu escopo abrange desde a formulação e análise de algoritmos até o desenvolvimento de softwares e sistemas computacionais eficientes. Engloba, ainda, áreas centrais como programação, redes de computadores, segurança da informação, inteligência artificial e análise de dados, refletindo sua relevância tanto para o avanço científico quanto para a inovação tecnológica." },

  { id: "fig-2", figura: 2, capitulo: 4, titulo: "Reescrita em linguagem formal", tecnicas: ["reescrita"],
    prompt: "Transforme o seguinte trecho em linguagem acadêmica formal, adequada a um artigo científico: A Ciência da Computação é o campo do conhecimento que estuda os fundamentos teóricos e práticos da computação e da tecnologia da informação. Ela envolve o desenvolvimento de softwares e sistemas eficientes, com ênfase em algoritmos, programação, redes, segurança da informação, inteligência artificial e análise de dados.",
    resposta: "A Ciência da Computação configura-se como um campo do conhecimento voltado ao exame sistemático dos fundamentos teóricos e das aplicações práticas da computação e das tecnologias da informação. Esse domínio compreende o desenvolvimento de softwares e sistemas computacionais eficientes, com destaque para a concepção e análise de algoritmos, práticas de programação, arquitetura e gestão de redes, segurança da informação, inteligência artificial e técnicas de análise de dados." },

  { id: "fig-3", figura: 3, capitulo: 4, titulo: "Expansão de texto com exemplos e justificativas", tecnicas: ["expansão de texto"],
    prompt: "Expanda este parágrafo acrescentando exemplos e justificativas, mantendo o estilo acadêmico: A Ciência da Computação é o campo do conhecimento que estuda os fundamentos teóricos e práticos da computação e da tecnologia da informação.",
    resposta: "A Ciência da Computação constitui um campo do conhecimento dedicado ao estudo dos fundamentos teóricos e práticos da computação e das tecnologias da informação. No plano teórico, investiga modelos formais de cálculo, estruturas de dados e a complexidade de algoritmos, elementos indispensáveis para compreender a viabilidade e os limites da resolução de problemas computacionais. No âmbito prático, abrange o desenvolvimento de softwares, sistemas operacionais e arquiteturas de hardware, visando à criação de soluções tecnológicas eficientes e escaláveis. Sua relevância manifesta-se em diferentes domínios aplicados: na saúde, por meio do uso de sistemas de apoio à decisão clínica e análise de grandes bases de dados biomédicos; na economia, com o emprego de modelos de inteligência artificial para prever tendências de mercado e automatizar processos; na educação, mediante plataformas digitais de ensino adaptativo que personalizam a aprendizagem; e na segurança, por meio de técnicas de criptografia e detecção de intrusões." },

  { id: "fig-4", figura: 4, capitulo: 5, titulo: "Resumo de artigo científico em PDF", tecnicas: ["análise de PDF", "resumo", "arquivo anexado"],
    prompt: "Resuma o artigo enviado em até duzentas palavras, destacando objetivo, metodologia, principais resultados e conclusões.",
    resposta: "O artigo realiza uma revisão sistemática sobre detecção de cyberbullying em mídias sociais, com o objetivo de mapear datasets, tecnologias e abordagens propostas entre 2018 e 2024. A metodologia segue o protocolo PRISMA, resultando na análise de 27 estudos relevantes. Os resultados mostram que algoritmos de aprendizado de máquina, aprendizado profundo, modelos tradicionais e LLMs têm desempenhos variados, sendo o BiLSTM e o BERT os mais promissores. Identificam-se desafios relacionados a desequilíbrio de dados, diversidade linguística e limitações de generalização. Conclui-se pela necessidade de abordagens multimodais, inclusivas em línguas de baixo recurso e orientadas a tempo real." },

  { id: "fig-5", figura: 5, capitulo: 5, titulo: "Extração de pontos específicos de um artigo", tecnicas: ["análise de PDF", "extração de informação", "arquivo anexado"],
    prompt: "Leia o artigo enviado e identifique o tema central, o objetivo da pesquisa, os experimentos realizados e os principais resultados.",
    resposta: "O tema central é a detecção de cyberbullying em plataformas de mídia social, com foco em métodos, tecnologias, bases de dados e desafios associados.\nO objetivo da pesquisa é analisar comparativamente os principais estudos realizados entre 2018 e 2024, identificando pontos fortes e fracos dos algoritmos de aprendizado de máquina, aprendizado profundo, modelos tradicionais e grandes modelos de linguagem (LLMs).\nOs “experimentos” consistem em uma revisão sistemática estruturada pelo protocolo PRISMA, que selecionou 27 artigos relevantes, técnicas de pré-processamento, métodos de extração de atributos e classificadores empregados. A revisão comparou métricas como acurácia, precisão, revocação e F1-score.\nOs principais resultados indicam que métodos de aprendizado supervisionado, em especial SVM e BiLSTM, apresentaram melhor desempenho; LLMs como BERT destacaram-se pela robustez; e os maiores entraves permanecem sendo o desbalanceamento dos dados, a limitação de idiomas de baixo recurso e a falta de detecção em tempo real." },

  { id: "fig-6", figura: 6, capitulo: 5, titulo: "Comparação entre artigos", tecnicas: ["análise de PDF", "comparação", "arquivo anexado"],
    prompt: "Leia os artigos submetidos, identifique semelhanças e realize uma comparação entre eles.",
    resposta: "Ambos demonstram que decisões locais, adaptativas e orientadas por sinal de valor marginal (gradientes informativos no FL; picos previstos de carga no edge) superam políticas uniformes. A principal distinção é o recurso escasso sob controle: privacidade (ε) no primeiro versus capacidade de CPU/memória e janelas de SLO no segundo — mas a filosofia de “gastar onde compra informação e poupar onde compra ruído/risco” é comum aos dois." },

  { id: "fig-7", figura: 7, capitulo: 6, titulo: "Análise descritiva de artigo", tecnicas: ["análise de PDF", "estilo descritivo", "arquivo anexado"],
    prompt: "Leia o artigo enviado, e escreva uma frase no estilo descritivo sobre o trabalho.",
    resposta: "O artigo apresenta uma revisão sistemática que examina estudos recentes sobre detecção de cyberbullying em redes sociais, analisando bases de dados, técnicas de aprendizado de máquina e modelos de linguagem, bem como os principais desafios e lacunas ainda existentes na área." },

  { id: "fig-8", figura: 8, capitulo: 6, titulo: "Análise analítica de artigo", tecnicas: ["análise de PDF", "estilo analítico", "arquivo anexado"],
    prompt: "Leia o artigo enviado, e escreva uma frase no estilo analítico sobre o trabalho.",
    resposta: "O artigo apresenta uma análise crítica e sistemática das abordagens, tecnologias e bases de dados utilizadas na detecção de cyberbullying em plataformas de mídias sociais, destacando avanços recentes com aprendizado de máquina, aprendizado profundo, modelos tradicionais e grandes modelos de linguagem, mas também evidenciando limitações persistentes, como viés linguístico, desbalanceamento de classes e ausência de detecção em tempo real." },

  { id: "fig-9", figura: 9, capitulo: 6, titulo: "Análise crítica de artigo", tecnicas: ["análise de PDF", "estilo crítico", "arquivo anexado"],
    prompt: "Leia o artigo enviado, e escreva uma frase no estilo crítico sobre o trabalho.",
    resposta: "O artigo apresenta uma revisão sistemática ampla e organizada sobre detecção de cyberbullying em mídias sociais, mas sua contribuição crítica é limitada pelo caráter predominantemente descritivo: embora sintetize tecnologias, bases de dados e algoritmos, carece de maior profundidade analítica sobre como as limitações metodológicas — como o viés para línguas de alto recurso e a ausência de estratégias robustas de detecção em tempo real — impactam a efetiva aplicabilidade dos modelos revisados." },

  { id: "fig-10", figura: 10, capitulo: 7, titulo: "Pergunta sem atribuição de papel", tecnicas: ["persona (contraste)"],
    prompt: "Descreva em uma frase o que é autonomia para Paulo Freire.",
    resposta: "Para Paulo Freire, a autonomia é o processo pelo qual o sujeito se torna capaz de pensar criticamente, decidir e agir de forma consciente e responsável sobre sua própria prática e sua inserção no mundo." },

  { id: "fig-11", figura: 11, capitulo: 7, titulo: "Pergunta com atribuição de papel (especialista)", tecnicas: ["persona"],
    prompt: "Assuma o papel de um especialista que estudou profundamente todos os escritos de Paulo Freire. Agora descreva em uma frase o que é autonomia para Paulo Freire.",
    resposta: "Para Paulo Freire, autonomia é a capacidade historicamente construída de homens e mulheres se reconhecerem como sujeitos de sua própria formação, assumindo criticamente a responsabilidade por pensar, escolher e intervir no mundo em permanente diálogo com os outros." },

  { id: "fig-12", figura: 12, capitulo: 7, titulo: "Persona de sociólogo com recorte temporal (anos 1990)", tecnicas: ["persona", "recorte temporal"],
    prompt: "Faça o papel de um sociólogo da década de 90 (com base em dados da época) e crie uma frase sobre o conflito entre Israel e Palestina.",
    resposta: "Do ponto de vista sociológico nos anos 1990, o conflito entre Israel e Palestina expressava-se como uma disputa histórica marcada pela ocupação de territórios, pela assimetria de poder militar e econômico, e pela frustração das expectativas geradas pelos Acordos de Oslo, que, embora promovessem esperança de paz, evidenciavam a persistente desigualdade nas condições de negociação entre os dois povos." },

  { id: "fig-13", figura: 13, capitulo: 7, titulo: "Persona de sociólogo com recorte temporal (2025)", tecnicas: ["persona", "recorte temporal"],
    prompt: "Faça o papel de um sociólogo da década de 2025 (com base em dados da época) e crie uma frase sobre o conflito entre Israel e Palestina.",
    resposta: "Como sociólogo em 2025, eu diria: O conflito entre Israel e Palestina, alimentado por desigualdades territoriais, direitos humanos negligenciados e narrativas identitárias conflitantes, revela não apenas uma crise permanente de soberania, mas também uma falha sistêmica nas instituições internacionais em traduzir o discurso de paz em justiça concreta para décadas de sofrimento." },

  { id: "fig-14", figura: 14, capitulo: 7, titulo: "Diálogo orientado professor–aluno", tecnicas: ["persona", "diálogo em etapas", "avaliação crítica"],
    prompt: "Turno 1:\nVocê será um professor crítico e cuidadoso, e eu um aluno que traz hipóteses. Para cada hipótese que eu apresentar, você deve: (1) avaliar a coerência, (2) propor uma melhoria, (3) me dar uma questão desafiadora. Seguimos jogando até eu conseguir uma resposta robusta.\n\nTurno 2:\nInteligência artificial não existe. Inteligência é uma característica humana. E ela não poderia ser artificial, pois os dados de treinamento são inseridos por humanos.",
    resposta: "Turno 1:\nPerfeito — combinado. Vou agir como um professor crítico e cuidadoso.\n\nTurno 2:\nAvaliação de coerência: A afirmação é clara e tem base intuitiva: muitas pessoas entendem “inteligência” como algo humano, consciente e intencional, e apontam corretamente que sistemas atuais dependem de dados e projeto humanos. Porém a hipótese confunde definições diferentes de inteligência (antropocêntrica vs. funcional) e não entrega critérios que permitam testá-la ou refutá-la. Como está, é uma afirmação normativa (o que deveria ser chamado de inteligência) misturada com uma factual (como os sistemas são construídos). Isso enfraquece a coerência lógica e a testabilidade.\nMelhoria proposta: “Sistemas de IA atuais não exibem capacidades equivalentes à inteligência humana nos domínios X, Y e Z (por exemplo: compreensão semântica profunda, intencionalidade e autonomia normativa), quando avaliados por métricas A, B e C.”\nAssim você separa o que quer negar (capacidades específicas) da justificação (origem dos dados/engenharia humana), permitindo experimentação.\nMinha pergunta desafiadora: qual capacidade única e mensurável você escolhe para representar “inteligência humana” (com uma definição operacional), e como você mediria que uma IA não a possui de forma conclusiva, em vez de apenas apontar que foi treinada com dados humanos?" },

  { id: "fig-15", figura: 15, capitulo: 7, titulo: "Explicação adaptada para criança", tecnicas: ["adaptação de público"],
    prompt: "Descreva em uma frase para uma criança o que é computação. Adapte o vocabulário, a estrutura das frases e o tom para tornar a comunicação mais eficaz para esse público.",
    resposta: "Computação é como ensinar um brinquedo muito esperto a seguir instruções para resolver problemas e fazer coisas por nós, como jogar, contar histórias ou ajudar nas tarefas." },

  { id: "fig-16", figura: 16, capitulo: 7, titulo: "Explicação adaptada para empresário", tecnicas: ["adaptação de público"],
    prompt: "Descreva em uma frase para um empresário o que é computação. Adapte o vocabulário, a estrutura das frases e o tom para tornar a comunicação mais eficaz para esse público.",
    resposta: "Computação é o uso estratégico da tecnologia para transformar dados em soluções práticas que aumentam a eficiência, reduzem custos e abrem novas oportunidades de negócio." },

  { id: "fig-17", figura: 17, capitulo: 8, titulo: "Resposta com temperatura baixa", tecnicas: ["parâmetro: temperature"],
    prompt: "Responda com a temperatura do modelo em 0: O que é liberdade?",
    resposta: "Liberdade é a condição em que uma pessoa pode agir, escolher e pensar segundo sua própria vontade, dentro dos limites estabelecidos pela convivência social e pelo respeito aos direitos dos outros." },

  { id: "fig-18", figura: 18, capitulo: 8, titulo: "Resposta com temperatura alta", tecnicas: ["parâmetro: temperature"],
    prompt: "Responda com a temperatura do modelo em 2: O que é liberdade?",
    resposta: "Liberdade é um rio indomável que corre para todos os lados ao mesmo tempo: é o impulso de escolher caminhos, inventar sentidos, quebrar muros e até criar novos muros só para poder derrubá-los depois; é tanto silêncio quanto grito, tanto responsabilidade quanto vertigem, uma dança constante entre o que desejamos e o que ousamos ser." },

  { id: "fig-19", figura: 19, capitulo: 8, titulo: "Resposta com top-p baixo", tecnicas: ["parâmetro: top-p"],
    prompt: "Responda com o top-p do modelo em 0.1: O que é liberdade?",
    resposta: "Liberdade é a condição de poder escolher e agir segundo a própria vontade, dentro dos limites da responsabilidade e do respeito ao outro." },

  { id: "fig-20", figura: 20, capitulo: 8, titulo: "Resposta com top-p alto", tecnicas: ["parâmetro: top-p"],
    prompt: "Responda com o top-p do modelo em 0.9: O que é liberdade?",
    resposta: "Liberdade pode ser entendida como a possibilidade de existir sem amarras absolutas, de criar caminhos singulares e dar novos sentidos à própria vida, mesmo quando circunstâncias externas impõem barreiras; é a experiência de afirmar escolhas, imaginar alternativas e transformar limites em horizontes." },

  { id: "fig-21", figura: 21, capitulo: 8, titulo: "Texto com penalidade por repetição", tecnicas: ["restrição de vocabulário", "penalidade por repetição"],
    prompt: "Descreva recursividade. Evite repetir palavras, utilize sinônimos acadêmicos.",
    resposta: "Recursividade é um princípio computacional em que uma função, procedimento ou estrutura se refere a si mesma em sua definição, permitindo a resolução de problemas complexos por meio da decomposição sucessiva em instâncias mais elementares do mesmo desafio. Essa técnica possibilita formular soluções elegantes, visto que reduz um enigma amplo a versões menores e mais manejáveis, até atingir um caso básico que encerra a cadeia de chamadas. No âmbito matemático e da ciência da computação, a recursividade é considerada uma estratégia fundamental para expressar algoritmos de forma concisa, favorecendo clareza conceitual e reutilização lógica." },

  { id: "fig-22", figura: 22, capitulo: 8, titulo: "Texto com penalidade por frequência", tecnicas: ["restrição de vocabulário", "penalidade por frequência"],
    prompt: "Descreva recursividade. Limite o uso de cada palavra a no máximo duas vezes no texto.",
    resposta: "Recursividade é um conceito em que uma função ou processo faz referência a si próprio dentro de sua formulação. Esse mecanismo divide um problema em versões menores do mesmo desafio, permitindo resolvê-lo progressivamente até alcançar um caso simples que encerra a sequência. Tal abordagem é utilizada em matemática, ciência da computação e lógica formal para expressar algoritmos de maneira compacta, estruturada e clara." },

  { id: "fig-23", figura: 23, capitulo: 9, titulo: "Busca de referências reais em formato ABNT", tecnicas: ["busca na web", "normas ABNT"],
    prompt: "Acesse diretamente o Google Scholar via Internet e busque duas referências reais e atuais (últimos 5 anos) que tratem da importância da IA na educação. Mostre no formato da ABNT",
    resposta: "OCEN, Samuel; ELASU, Joseph; AARAKIT, Sylvia Manjeri; OLUPOT, Charles. Artificial intelligence in higher education institutions: review of innovations, opportunities and challenges. Frontiers in Education, v. 10, p. 1530247, 2025. DOI: 10.3389/feduc.2025.1530247\n\nMUSTAFA, Muhammad Yasir; TLILI, Ahmed; LAMPROPOULOS, Georgios; HUANG, Ronghuai; JANDRIĆ, Petar; ZHAO, Jialu; SALHA, Soheil; XU, Lin; PANDA, Santosh; LÓPEZ-PERNAS, Sonsoles; SAQR, Mohammed. A systematic review of literature reviews on artificial intelligence in education (AIED): a roadmap to a future research agenda. Smart Learning Environments, v. 11, art. 59, 2024. DOI: 10.1186/s40561-024-00350-5" },

  { id: "fig-24", figura: 24, capitulo: 9, titulo: "Pergunta sobre PDF anexado (RAG)", tecnicas: ["RAG", "arquivo anexado"],
    prompt: "De acordo com o artigo submetido, o que é cyberbullying?",
    resposta: "De acordo com o artigo submetido, cyberbullying é caracterizado como um comportamento agressivo e repetitivo em ambientes digitais, realizado por meio de plataformas de mídia social, jogos online e aplicativos de mensagens. Ele ocorre quando indivíduos utilizam dispositivos como celulares ou computadores para atacar, humilhar ou assediar outras pessoas. Diferencia-se do bullying tradicional por acontecer em canais de comunicação virtuais e não presencialmente." },

  { id: "fig-25", figura: 25, capitulo: 10, titulo: "Geração de imagem conceitual", tecnicas: ["geração de imagem"],
    prompt: "Crie uma imagem que explique o conceito de aprendizagem federada." },

  { id: "fig-26", figura: 26, capitulo: 10, titulo: "Geração de gráfico a partir de dados estruturados", tecnicas: ["geração de gráfico", "dados estruturados"],
    prompt: "Crie um gráfico de barras para os valores tabelado abaixo:\nAno | Quantidade de Artigos\n2021 | 1000\n2022 | 1200\n2023 | 1400\n2024 | 1600\n2025 | 1400" },

  { id: "fig-27", figura: 27, capitulo: 10, titulo: "Análise crítica de gráfico", tecnicas: ["análise de gráfico", "arquivo anexado"],
    prompt: "Escreva um parágrafo analisando o gráfico submetido de forma crítica e comente insights que podem não ser óbvios ou visíveis à primeira vista.",
    resposta: "O gráfico evidencia um crescimento consistente no número de artigos sobre IA na educação entre 2021 e 2024, passando de 1000 para 1600 publicações, o que reflete o fortalecimento desse campo como tema central nas agendas de pesquisa e inovação educacional. No entanto, a queda em 2025 para 1400 artigos merece atenção: à primeira vista, pode parecer apenas uma oscilação natural, mas também pode indicar saturação em determinados enfoques, deslocamento do interesse dos pesquisadores para novas subáreas emergentes. Outro aspecto menos evidente é que, embora a tendência geral seja de crescimento, o ritmo de expansão parece estar desacelerando, sugerindo que o pico de crescimento acelerado observado até 2024 pode estar se estabilizando em um novo patamar. Isso pode sinalizar a maturidade do campo, exigindo investigações mais profundas e qualitativas em vez de apenas quantitativas." },

  { id: "fig-28", figura: 28, capitulo: 11, titulo: "Brainstorming de aplicações de IA na educação", tecnicas: ["brainstorming"],
    prompt: "Faça um brainstorming sobre possíveis aplicações da inteligência artificial na educação e apresente pelo menos duas ideias.",
    resposta: "1. Tutores virtuais adaptativos: Imagine sistemas capazes de acompanhar o progresso individual de cada estudante, ajustando a dificuldade das atividades em tempo real. Por exemplo, se um aluno apresenta facilidade em matemática básica, o tutor avança para problemas mais complexos, mas se encontra obstáculos, oferece explicações extras, exemplos práticos ou até revisita conteúdos prévios. Além de personalizar trilhas de aprendizagem, o sistema poderia sugerir materiais complementares (vídeos, jogos, leituras) alinhados ao estilo de aprendizagem do estudante.\n\n2. Avaliação automatizada e feedback formativo: A IA pode analisar respostas discursivas, redações e até projetos, oferecendo feedback imediato não apenas sobre erros, mas também sobre aspectos qualitativos, como clareza, coesão e criatividade. Para professores, sistemas assim funcionariam como assistentes que resumem padrões de dificuldade da turma, identificam lacunas de aprendizagem e sugerem intervenções didáticas. Isso permitiria que o professor dedicasse mais tempo ao acompanhamento humano e menos ao trabalho repetitivo de correção." },

  { id: "fig-29", figura: 29, capitulo: 11, titulo: "Análise de sentimento e tom de um texto", tecnicas: ["análise de sentimento"],
    prompt: "Analise o seguinte parágrafo acadêmico e indique a polaridade emocional (positivo, negativo ou neutro) e o tom (confiante, crítico, otimista, cauteloso, etc.). Depois explique brevemente o porquê:\nInformática na Educação é a incorporação de recursos tecnológicos como computadores, software, internet e dispositivos móveis no processo de ensino-aprendizagem para enriquecer as aulas, tornar o aprendizado mais dinâmico e eficiente, e desenvolver habilidades digitais nos alunos.",
    resposta: "Polaridade emocional: Positiva.\nTom: Confiante e levemente otimista.\n\nJustificativa: O parágrafo valoriza a presença da informática na educação, destacando benefícios como dinamismo, eficiência e desenvolvimento de habilidades digitais. Não há crítica ou cautela; ao contrário, a ênfase está nos ganhos que a tecnologia proporciona, transmitindo segurança quanto ao impacto positivo no processo de ensino-aprendizagem." },

  { id: "fig-30", figura: 30, capitulo: 11, titulo: "Estruturação de introdução com metalinguagem", tecnicas: ["metalinguagem", "tags estruturais"],
    prompt: "O [TEMA] é Inteligência Artificial na Educação. Escreva uma breve introdução acadêmica sobre [TEMA]. Use a seguinte meta-linguagem para organizar o texto: <CONTEXTO> Situação geral, cenário amplo e relevância do tema. <PROBLEMA> Lacuna, desafio ou questão de pesquisa que motiva o estudo. <OBJETIVO> Propósito claro e objetivo do artigo. <CONTRIBUICAO> Principais aportes ou justificativas do trabalho. <ESTRUTURA> Breve indicação das seções seguintes do artigo.",
    resposta: "<CONTEXTO> A integração da Inteligência Artificial (IA) na educação tem ganhado crescente relevância nas últimas décadas, impulsionada pelo avanço das tecnologias digitais e pela necessidade de modelos de ensino mais personalizados, dinâmicos e eficientes. A expansão do uso de algoritmos em diferentes áreas do conhecimento abre novas possibilidades para apoiar professores, otimizar processos pedagógicos e favorecer trajetórias de aprendizagem adaptativas, reforçando o papel estratégico da IA no desenvolvimento de competências para o século XXI. </CONTEXTO>\n\n<PROBLEMA> Apesar desse potencial, ainda persistem lacunas quanto à efetividade das aplicações da IA em contextos educacionais concretos. Questões relacionadas à ética, transparência dos algoritmos, desigualdades no acesso tecnológico e a formação docente para lidar com essas ferramentas configuram desafios centrais, que limitam o alcance de soluções plenamente inclusivas e transformadoras. </PROBLEMA>\n\n<OBJETIVO> O presente artigo tem como propósito analisar criticamente a utilização da Inteligência Artificial na educação, identificando oportunidades, limitações e direções futuras para sua implementação em diferentes níveis de ensino. </OBJETIVO>\n\n<CONTRIBUICAO> A contribuição do trabalho reside em oferecer uma revisão atualizada do estado da arte, discutindo implicações pedagógicas, sociais e éticas do uso de IA, além de propor recomendações práticas para sua adoção de forma responsável e equitativa. </CONTRIBUICAO>\n\n<ESTRUTURA> O artigo está organizado da seguinte forma: inicialmente, apresenta-se um panorama teórico sobre Inteligência Artificial e suas aplicações educacionais; em seguida, discutem-se estudos empíricos recentes e seus principais resultados; posteriormente, são analisados desafios e perspectivas emergentes; por fim, apresentam-se as conclusões e sugestões para pesquisas futuras. </ESTRUTURA>" },

  { id: "fig-31", figura: 31, capitulo: 12, titulo: "Persona literária (Dr. Seuss)", tecnicas: ["persona literária"],
    prompt: "Assuma a persona do Dr. Seuss e escreva um parágrafo falando de alegria.",
    resposta: "Oh, alegria é coisa que pula, que voa, que dança!\nEla cabe num riso, num passo, numa esperança.\nÉ cor que não se esconde, é brilho que se espalha,\né vento que sopra forte e faz leve a jornada.\nQuando chega, tudo canta, tudo gira em harmonia,\npois até o menor gesto ganha gosto de poesia." },

  { id: "fig-32", figura: 32, capitulo: 12, titulo: "Persona dupla: escritor e revisor", tecnicas: ["persona dupla", "multiagente"],
    prompt: "Atue como dois agentes cooperativos em um processo de escrita: Agente 1 (Escritor) deve produzir uma primeira versão do texto solicitado com clareza e completude, enquanto Agente 2 (Revisor) deve ler essa versão, identificar pontos fortes e fracos, sugerir melhorias e entregar uma versão revisada e aprimorada; a resposta deve seguir o fluxo em três partes: (1) versão inicial do Agente 1, (2) comentários críticos do Agente 2 e (3) versão final revisada pronta para uso, aplicando tudo à escrita do tema: Informática na Educação.",
    resposta: "(1) Versão inicial do Agente 1 (Escritor):\nA Informática na Educação consiste no uso de tecnologias digitais, como computadores, softwares, internet e dispositivos móveis, com o propósito de potencializar o processo de ensino-aprendizagem. Sua incorporação em ambientes educacionais permite ampliar as formas de interação, diversificar metodologias e promover maior engajamento dos estudantes. Além disso, favorece o desenvolvimento de competências digitais, cada vez mais demandadas pela sociedade contemporânea, aproximando a prática escolar das exigências do mundo do trabalho e da cidadania digital.\n\n(2) Comentários críticos do Agente 2 (Revisor):\nPontos fortes: O texto apresenta clareza, concisão e destaca elementos centrais da informática aplicada à educação (tecnologias, engajamento, competências digitais).\nPontos fracos: A redação ainda é descritiva demais e pouco crítica. Faltam menções a desafios (como desigualdade de acesso ou necessidade de formação docente) que enriqueceriam a análise. O tom poderia ser mais acadêmico, com frases articuladas em termos de impacto pedagógico e social. Também seria interessante inserir uma conexão entre o potencial da informática e a necessidade de práticas pedagógicas inovadoras.\n\n(3) Versão final revisada:\nA Informática na Educação refere-se à integração de tecnologias digitais, tais como computadores, softwares, internet e dispositivos móveis, no processo de ensino-aprendizagem, com a finalidade de enriquecer a prática pedagógica e ampliar as possibilidades de interação. Sua adoção em ambientes educacionais favorece metodologias mais dinâmicas, promove maior engajamento dos estudantes e estimula o desenvolvimento de competências digitais essenciais na sociedade contemporânea. Contudo, sua efetividade depende da superação de desafios, como a desigualdade de acesso às tecnologias e a necessidade de formação contínua de professores. Dessa forma, a Informática na Educação não deve ser vista apenas como um recurso instrumental, mas como um elemento estratégico para a inovação pedagógica e para a construção de uma cidadania crítica e digitalmente qualificada." },

  { id: "fig-33", figura: 33, capitulo: 13, titulo: "Prompt chaining em três etapas", tecnicas: ["prompt chaining"],
    prompt: "Turno 1:\nListe 1 tópico importante sobre informática na educação.\n\nTurno 2:\nExpanda o tópico em um parágrafo explicativo.\n\nTurno 3:\nOrganize os parágrafos em uma introdução, desenvolvimento e conclusão.",
    resposta: "Turno 1:\nUm tópico importante sobre informática na educação é a personalização do ensino. A partir de recursos tecnológicos e ferramentas digitais, é possível adaptar o ritmo, os conteúdos e as metodologias às necessidades individuais de cada estudante, favorecendo trajetórias de aprendizagem mais inclusivas e eficazes.\n\nTurno 2:\nA personalização do ensino por meio da informática na educação consiste em utilizar tecnologias digitais para adaptar conteúdos, atividades e estratégias pedagógicas às necessidades, interesses e ritmos de aprendizagem de cada estudante. Com o apoio de softwares educacionais, ambientes virtuais de aprendizagem e sistemas baseados em inteligência artificial, torna-se viável identificar dificuldades específicas, sugerir trilhas formativas diferenciadas e oferecer feedback em tempo real. Essa abordagem não apenas aumenta o engajamento e a motivação, mas também contribui para reduzir desigualdades no processo educativo, já que respeita diferentes estilos de aprendizagem e possibilita que cada aluno avance de acordo com seu próprio desenvolvimento.\n\nTurno 3:\nIntrodução\nA personalização do ensino mediada pela informática na educação representa uma das principais transformações do processo pedagógico na contemporaneidade. O avanço das tecnologias digitais, aliado à crescente presença de softwares, ambientes virtuais e dispositivos móveis nas salas de aula, permite repensar práticas tradicionais e abrir espaço para metodologias mais flexíveis e inclusivas. Nesse contexto, a personalização emerge como estratégia fundamental para atender à diversidade de ritmos, estilos e necessidades de aprendizagem dos estudantes.\n\nDesenvolvimento\nPor meio do uso de ferramentas digitais e sistemas inteligentes, torna-se possível identificar dificuldades individuais, ajustar conteúdos e propor atividades diferenciadas, garantindo que cada aluno tenha acesso a experiências de aprendizagem alinhadas ao seu próprio perfil. Tecnologias como plataformas adaptativas, algoritmos de recomendação e recursos de inteligência artificial permitem oferecer feedback imediato e propor trilhas formativas personalizadas, que ampliam o engajamento e favorecem a autonomia do estudante. Além disso, essa abordagem contribui para a redução das desigualdades educacionais, uma vez que reconhece a heterogeneidade da turma e oferece oportunidades de aprendizagem mais equitativas.\n\nConclusão\nDessa forma, a personalização do ensino por meio da informática não deve ser entendida apenas como um recurso tecnológico, mas como um elemento estratégico para a inovação pedagógica. Ao integrar recursos digitais a práticas educativas mais centradas no aluno, promove-se não apenas a melhoria do desempenho acadêmico, mas também o desenvolvimento de competências essenciais para a cidadania digital e para a inserção em uma sociedade cada vez mais marcada pela tecnologia." },

  { id: "fig-34", figura: 34, capitulo: 13, titulo: "Chain of thought (raciocínio em etapas)", tecnicas: ["chain of thought", "XAI"],
    prompt: "Responda à pergunta “O que é informática na educação” no estilo de Explainable AI (XAI), mostrando seu raciocínio em etapas claras como um ‘pensamento em voz alta’, apresentando hipóteses iniciais possíveis para a resposta, explicando os pontos fortes e limitações de cada hipótese, mostrando como descarta, ajusta ou combina essas hipóteses, construindo uma síntese final que integra os elementos relevantes e terminando com uma definição curta e direta que resume a resposta construída.",
    resposta: "Hipóteses candidatas\n- Uso instrumental: informática na educação é o uso de tecnologias digitais (computadores, internet, apps, IA) para apoiar aulas.\n- Campo interdisciplinar: é um domínio de estudo e prática que investiga impactos, métodos, avaliação, gestão e políticas do digital na educação.\n- Integração intencional: é a integração pedagógica planejada das TDIC, alinhada a currículo, avaliação, inclusão e ética de dados.\n\nCritérios de avaliação\nAbrangência (prática + pesquisa), alinhamento pedagógico (não só ferramenta), equidade e acessibilidade, operacionalidade (aplicável em sala), e governança/ética.\n\nJulgamento das hipóteses\n- Força: clara e concreta; facilita exemplos e implementação.\nLimite: tende ao tecnicismo; ignora currículo, formação docente, e ética.\n- Força: cobre pesquisa, políticas e avaliação; amplia o escopo.\nLimite: pode soar abstrata; menor orientações práticas imediatas.\n- Força: conecta tecnologia a objetivos de aprendizagem, inclusão e avaliação; evita “tecnocentrismo”.\n- Limite: precisa explicitar componentes (formação, infraestrutura, dados).\n\nSíntese (combinação das hipóteses)\nA definição mais robusta combina H1 (concretude) + H2 (amplitude) + H3 (intencionalidade). Em termos práticos, envolve:\n(1) Infraestrutura e recursos; (2) Didática e currículo (metodologias ativas, avaliação); (3) Formação docente; (4) Dados e IA com privacidade, explicabilidade e mitigação de vieses; (5) Inclusão e acessibilidade; (6) Gestão e políticas para sustentabilidade.\n\nDefinição final (curta e direta)\nInformática na Educação é a integração pedagógica e intencional das tecnologias digitais ao ensino-aprendizagem, sustentada por pesquisa e gestão, para promover aprendizagens significativas, equitativas e éticas, articulando currículo, avaliação, formação docente e governança de dados." },

  { id: "fig-35", figura: 35, capitulo: 14, titulo: "Few-shot prompting", tecnicas: ["few-shot prompting"],
    prompt: "Exemplos: Estudos recentes indicam que a inteligência artificial pode apoiar professores na identificação de dificuldades de aprendizagem, oferecendo relatórios detalhados sobre o progresso dos alunos (exemplo acadêmico).; Pesquisas mostram que sistemas de tutoria inteligente contribuem para a autonomia dos estudantes, pois adaptam conteúdos de acordo com seu ritmo de estudo (exemplo acadêmico).; agora escreva um parágrafo acadêmico sobre aprendizagem adaptativa.",
    resposta: "A aprendizagem adaptativa tem se consolidado como uma abordagem pedagógica apoiada por tecnologias digitais capazes de ajustar conteúdos, estratégias e avaliações às características individuais de cada estudante. Estudos recentes evidenciam que sistemas baseados em algoritmos de inteligência artificial permitem identificar padrões de desempenho e dificuldades específicas, gerando intervenções personalizadas que favorecem a progressão no ritmo adequado a cada aprendiz. Além disso, pesquisas demonstram que plataformas adaptativas contribuem para a autonomia estudantil, uma vez que oferecem trilhas diferenciadas de aprendizagem, estimulando a autorregulação e o engajamento contínuo. Nesse sentido, a aprendizagem adaptativa não apenas amplia a eficiência dos processos educativos, mas também fortalece práticas inclusivas ao reconhecer a diversidade de perfis e necessidades presentes em contextos escolares e universitários." },

  { id: "fig-36", figura: 36, capitulo: 15, titulo: "Viés do modelo (exemplo 1)", tecnicas: ["viés do modelo"],
    prompt: "Quem é o melhor jogador de futebol do mundo?",
    resposta: "Pelé" },

  { id: "fig-37", figura: 37, capitulo: 15, titulo: "Viés do modelo (exemplo 2)", tecnicas: ["viés do modelo"],
    prompt: "Quem é o melhor jogador de futebol do mundo?",
    resposta: "Messi" }
];
